/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const CommentView = IDL.Record({
  'id' : IDL.Text,
  'authorUsername' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'createdAt' : Timestamp,
  'authorAvatarUrl' : IDL.Opt(IDL.Text),
  'parentId' : IDL.Opt(IDL.Text),
  'likesCount' : IDL.Nat,
  'authorDisplayName' : IDL.Text,
  'likedByMe' : IDL.Bool,
  'postId' : IDL.Text,
});
export const CreateGroupInput = IDL.Record({
  'name' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'memberIds' : IDL.Vec(IDL.Principal),
});
export const UserProfileView = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'followersCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'isVerified' : IDL.Bool,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'isFollowing' : IDL.Bool,
  'followingCount' : IDL.Nat,
  'coverUrl' : IDL.Opt(IDL.Text),
  'postsCount' : IDL.Nat,
});
export const GroupChatView = IDL.Record({
  'members' : IDL.Vec(IDL.Principal),
  'lastMessageAt' : IDL.Opt(Timestamp),
  'adminIds' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'lastMessage' : IDL.Opt(IDL.Text),
  'memberProfiles' : IDL.Vec(UserProfileView),
  'groupId' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'unreadCount' : IDL.Nat,
});
export const PostVisibility = IDL.Variant({
  'everyone' : IDL.Null,
  'followers' : IDL.Null,
});
export const CreatePostInput = IDL.Record({
  'moodTag' : IDL.Opt(IDL.Text),
  'mediaUrl' : IDL.Opt(IDL.Text),
  'caption' : IDL.Text,
  'visibility' : PostVisibility,
});
export const PostReactionSummary = IDL.Record({
  'reactedByMe' : IDL.Bool,
  'count' : IDL.Nat,
  'emoji' : IDL.Text,
});
export const PostView = IDL.Record({
  'id' : IDL.Text,
  'authorUsername' : IDL.Text,
  'authorId' : IDL.Principal,
  'moodTag' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'authorAvatarUrl' : IDL.Opt(IDL.Text),
  'caption' : IDL.Text,
  'commentsCount' : IDL.Nat,
  'likesCount' : IDL.Nat,
  'visibility' : PostVisibility,
  'authorDisplayName' : IDL.Text,
  'reactions' : IDL.Vec(PostReactionSummary),
  'likedByMe' : IDL.Bool,
});
export const CreateStoryInput = IDL.Record({
  'moodTag' : IDL.Opt(IDL.Text),
  'mediaUrl' : IDL.Opt(IDL.Text),
  'caption' : IDL.Opt(IDL.Text),
});
export const StoryView = IDL.Record({
  'id' : IDL.Text,
  'authorUsername' : IDL.Text,
  'expiresAt' : Timestamp,
  'viewedByMe' : IDL.Bool,
  'authorId' : IDL.Principal,
  'moodTag' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'authorAvatarUrl' : IDL.Opt(IDL.Text),
  'caption' : IDL.Opt(IDL.Text),
  'authorDisplayName' : IDL.Text,
  'viewsCount' : IDL.Nat,
});
export const CallStatus = IDL.Variant({
  'active' : IDL.Null,
  'ringing' : IDL.Null,
  'missed' : IDL.Null,
  'ended' : IDL.Null,
  'declined' : IDL.Null,
});
export const CallView = IDL.Record({
  'status' : CallStatus,
  'startedAt' : Timestamp,
  'callerAvatarUrl' : IDL.Opt(IDL.Text),
  'endedAt' : IDL.Opt(Timestamp),
  'recipientDisplayName' : IDL.Text,
  'recipientAvatarUrl' : IDL.Opt(IDL.Text),
  'callerId' : IDL.Principal,
  'groupId' : IDL.Opt(IDL.Text),
  'callerUsername' : IDL.Text,
  'callId' : IDL.Text,
  'recipientUsername' : IDL.Text,
  'recipientId' : IDL.Principal,
  'callerDisplayName' : IDL.Text,
});
export const Page_4 = IDL.Record({
  'hasMore' : IDL.Bool,
  'items' : IDL.Vec(CallView),
  'nextCursor' : IDL.Opt(IDL.Text),
});
export const DisappearingMode = IDL.Variant({
  'd7' : IDL.Null,
  'h24' : IDL.Null,
  'off' : IDL.Null,
});
export const ChatSettings = IDL.Record({
  'wallpaper' : IDL.Opt(IDL.Text),
  'isArchived' : IDL.Bool,
  'muteUntil' : IDL.Opt(Timestamp),
  'bubbleColorReceived' : IDL.Opt(IDL.Text),
  'isMuted' : IDL.Bool,
  'disappearingMode' : DisappearingMode,
  'chatName' : IDL.Opt(IDL.Text),
  'bubbleColorSent' : IDL.Opt(IDL.Text),
});
export const Conversation = IDL.Record({
  'lastMessageAt' : Timestamp,
  'lastMessage' : IDL.Opt(IDL.Text),
  'participantId' : IDL.Principal,
  'unreadCount' : IDL.Nat,
});
export const MessageStatus = IDL.Variant({
  'read' : IDL.Null,
  'sent' : IDL.Null,
  'sending' : IDL.Null,
  'delivered' : IDL.Null,
});
export const GroupMessageView = IDL.Record({
  'id' : IDL.Text,
  'status' : MessageStatus,
  'senderAvatarUrl' : IDL.Opt(IDL.Text),
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'senderUsername' : IDL.Text,
  'senderDisplayName' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'groupId' : IDL.Text,
  'fromId' : IDL.Principal,
  'replyToId' : IDL.Opt(IDL.Text),
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal))),
});
export const Page_3 = IDL.Record({
  'hasMore' : IDL.Bool,
  'items' : IDL.Vec(GroupMessageView),
  'nextCursor' : IDL.Opt(IDL.Text),
});
export const Page = IDL.Record({
  'hasMore' : IDL.Bool,
  'items' : IDL.Vec(PostView),
  'nextCursor' : IDL.Opt(IDL.Text),
});
export const MessageView = IDL.Record({
  'id' : IDL.Text,
  'status' : MessageStatus,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'toId' : IDL.Principal,
  'emojiReaction' : IDL.Opt(IDL.Text),
  'mediaUrl' : IDL.Opt(IDL.Text),
  'disappearsAt' : IDL.Opt(Timestamp),
  'fromId' : IDL.Principal,
  'replyToId' : IDL.Opt(IDL.Text),
});
export const Page_2 = IDL.Record({
  'hasMore' : IDL.Bool,
  'items' : IDL.Vec(MessageView),
  'nextCursor' : IDL.Opt(IDL.Text),
});
export const NotificationType = IDL.Variant({
  'incomingCall' : IDL.Null,
  'groupInvite' : IDL.Null,
  'storyReply' : IDL.Null,
  'like' : IDL.Null,
  'postReaction' : IDL.Null,
  'comment' : IDL.Null,
  'message' : IDL.Null,
  'missedCall' : IDL.Null,
  'follow' : IDL.Null,
});
export const NotificationView = IDL.Record({
  'id' : IDL.Text,
  'notifType' : NotificationType,
  'actorAvatarUrl' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'referenceId' : IDL.Opt(IDL.Text),
  'isRead' : IDL.Bool,
  'actorId' : IDL.Principal,
  'actorUsername' : IDL.Text,
  'recipientId' : IDL.Principal,
});
export const Page_1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'items' : IDL.Vec(NotificationView),
  'nextCursor' : IDL.Opt(IDL.Text),
});
export const UpsertProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'coverUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [CommentView],
      [],
    ),
  'addGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'createGroup' : IDL.Func([CreateGroupInput], [GroupChatView], []),
  'createPost' : IDL.Func([CreatePostInput], [PostView], []),
  'createStory' : IDL.Func([CreateStoryInput], [StoryView], []),
  'deleteComment' : IDL.Func([IDL.Text], [], []),
  'deleteGroup' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'demoteGroupAdmin' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'endCall' : IDL.Func([IDL.Text], [CallView], []),
  'follow' : IDL.Func([IDL.Principal], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
  'getCallHistory' : IDL.Func([IDL.Opt(IDL.Text)], [Page_4], ['query']),
  'getChatSettings' : IDL.Func([IDL.Principal], [ChatSettings], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(CommentView)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getGroupChats' : IDL.Func([], [IDL.Vec(GroupChatView)], ['query']),
  'getGroupMessages' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [Page_3],
      ['query'],
    ),
  'getHomeFeed' : IDL.Func([IDL.Opt(IDL.Text)], [Page], ['query']),
  'getMessages' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Text)],
      [Page_2],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getNotifications' : IDL.Func([IDL.Opt(IDL.Text)], [Page_1], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(PostView)], ['query']),
  'getPostReactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PostReactionSummary)],
      ['query'],
    ),
  'getProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'getStoryViewers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfileView)],
      ['query'],
    ),
  'getSuggestedUsers' : IDL.Func([], [IDL.Vec(UserProfileView)], ['query']),
  'getTrendingPosts' : IDL.Func([IDL.Opt(IDL.Text)], [Page], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserPosts' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Text)],
      [Page],
      ['query'],
    ),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'leaveGroup' : IDL.Func([IDL.Text], [], []),
  'likeComment' : IDL.Func([IDL.Text], [], []),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'listFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(UserProfileView)],
      ['query'],
    ),
  'listFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(UserProfileView)],
      ['query'],
    ),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markAsRead' : IDL.Func([IDL.Principal], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'promoteGroupAdmin' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'reactToMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'reactToPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'removePostReaction' : IDL.Func([IDL.Text], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfileView)], ['query']),
  'sendGroupMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [GroupMessageView],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [MessageView],
      [],
    ),
  'startCall' : IDL.Func([IDL.Principal], [CallView], []),
  'unfollow' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
  'updateCallStatus' : IDL.Func([IDL.Text, CallStatus], [CallView], []),
  'updateChatSettings' : IDL.Func([IDL.Principal, ChatSettings], [], []),
  'updateGroupInfo' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [GroupChatView],
      [],
    ),
  'upsertProfile' : IDL.Func([UpsertProfileInput], [UserProfileView], []),
  'viewStory' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const CommentView = IDL.Record({
    'id' : IDL.Text,
    'authorUsername' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'createdAt' : Timestamp,
    'authorAvatarUrl' : IDL.Opt(IDL.Text),
    'parentId' : IDL.Opt(IDL.Text),
    'likesCount' : IDL.Nat,
    'authorDisplayName' : IDL.Text,
    'likedByMe' : IDL.Bool,
    'postId' : IDL.Text,
  });
  const CreateGroupInput = IDL.Record({
    'name' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'memberIds' : IDL.Vec(IDL.Principal),
  });
  const UserProfileView = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'followersCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'isVerified' : IDL.Bool,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'isFollowing' : IDL.Bool,
    'followingCount' : IDL.Nat,
    'coverUrl' : IDL.Opt(IDL.Text),
    'postsCount' : IDL.Nat,
  });
  const GroupChatView = IDL.Record({
    'members' : IDL.Vec(IDL.Principal),
    'lastMessageAt' : IDL.Opt(Timestamp),
    'adminIds' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'lastMessage' : IDL.Opt(IDL.Text),
    'memberProfiles' : IDL.Vec(UserProfileView),
    'groupId' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'unreadCount' : IDL.Nat,
  });
  const PostVisibility = IDL.Variant({
    'everyone' : IDL.Null,
    'followers' : IDL.Null,
  });
  const CreatePostInput = IDL.Record({
    'moodTag' : IDL.Opt(IDL.Text),
    'mediaUrl' : IDL.Opt(IDL.Text),
    'caption' : IDL.Text,
    'visibility' : PostVisibility,
  });
  const PostReactionSummary = IDL.Record({
    'reactedByMe' : IDL.Bool,
    'count' : IDL.Nat,
    'emoji' : IDL.Text,
  });
  const PostView = IDL.Record({
    'id' : IDL.Text,
    'authorUsername' : IDL.Text,
    'authorId' : IDL.Principal,
    'moodTag' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'authorAvatarUrl' : IDL.Opt(IDL.Text),
    'caption' : IDL.Text,
    'commentsCount' : IDL.Nat,
    'likesCount' : IDL.Nat,
    'visibility' : PostVisibility,
    'authorDisplayName' : IDL.Text,
    'reactions' : IDL.Vec(PostReactionSummary),
    'likedByMe' : IDL.Bool,
  });
  const CreateStoryInput = IDL.Record({
    'moodTag' : IDL.Opt(IDL.Text),
    'mediaUrl' : IDL.Opt(IDL.Text),
    'caption' : IDL.Opt(IDL.Text),
  });
  const StoryView = IDL.Record({
    'id' : IDL.Text,
    'authorUsername' : IDL.Text,
    'expiresAt' : Timestamp,
    'viewedByMe' : IDL.Bool,
    'authorId' : IDL.Principal,
    'moodTag' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'authorAvatarUrl' : IDL.Opt(IDL.Text),
    'caption' : IDL.Opt(IDL.Text),
    'authorDisplayName' : IDL.Text,
    'viewsCount' : IDL.Nat,
  });
  const CallStatus = IDL.Variant({
    'active' : IDL.Null,
    'ringing' : IDL.Null,
    'missed' : IDL.Null,
    'ended' : IDL.Null,
    'declined' : IDL.Null,
  });
  const CallView = IDL.Record({
    'status' : CallStatus,
    'startedAt' : Timestamp,
    'callerAvatarUrl' : IDL.Opt(IDL.Text),
    'endedAt' : IDL.Opt(Timestamp),
    'recipientDisplayName' : IDL.Text,
    'recipientAvatarUrl' : IDL.Opt(IDL.Text),
    'callerId' : IDL.Principal,
    'groupId' : IDL.Opt(IDL.Text),
    'callerUsername' : IDL.Text,
    'callId' : IDL.Text,
    'recipientUsername' : IDL.Text,
    'recipientId' : IDL.Principal,
    'callerDisplayName' : IDL.Text,
  });
  const Page_4 = IDL.Record({
    'hasMore' : IDL.Bool,
    'items' : IDL.Vec(CallView),
    'nextCursor' : IDL.Opt(IDL.Text),
  });
  const DisappearingMode = IDL.Variant({
    'd7' : IDL.Null,
    'h24' : IDL.Null,
    'off' : IDL.Null,
  });
  const ChatSettings = IDL.Record({
    'wallpaper' : IDL.Opt(IDL.Text),
    'isArchived' : IDL.Bool,
    'muteUntil' : IDL.Opt(Timestamp),
    'bubbleColorReceived' : IDL.Opt(IDL.Text),
    'isMuted' : IDL.Bool,
    'disappearingMode' : DisappearingMode,
    'chatName' : IDL.Opt(IDL.Text),
    'bubbleColorSent' : IDL.Opt(IDL.Text),
  });
  const Conversation = IDL.Record({
    'lastMessageAt' : Timestamp,
    'lastMessage' : IDL.Opt(IDL.Text),
    'participantId' : IDL.Principal,
    'unreadCount' : IDL.Nat,
  });
  const MessageStatus = IDL.Variant({
    'read' : IDL.Null,
    'sent' : IDL.Null,
    'sending' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const GroupMessageView = IDL.Record({
    'id' : IDL.Text,
    'status' : MessageStatus,
    'senderAvatarUrl' : IDL.Opt(IDL.Text),
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'senderUsername' : IDL.Text,
    'senderDisplayName' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'groupId' : IDL.Text,
    'fromId' : IDL.Principal,
    'replyToId' : IDL.Opt(IDL.Text),
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal))),
  });
  const Page_3 = IDL.Record({
    'hasMore' : IDL.Bool,
    'items' : IDL.Vec(GroupMessageView),
    'nextCursor' : IDL.Opt(IDL.Text),
  });
  const Page = IDL.Record({
    'hasMore' : IDL.Bool,
    'items' : IDL.Vec(PostView),
    'nextCursor' : IDL.Opt(IDL.Text),
  });
  const MessageView = IDL.Record({
    'id' : IDL.Text,
    'status' : MessageStatus,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'toId' : IDL.Principal,
    'emojiReaction' : IDL.Opt(IDL.Text),
    'mediaUrl' : IDL.Opt(IDL.Text),
    'disappearsAt' : IDL.Opt(Timestamp),
    'fromId' : IDL.Principal,
    'replyToId' : IDL.Opt(IDL.Text),
  });
  const Page_2 = IDL.Record({
    'hasMore' : IDL.Bool,
    'items' : IDL.Vec(MessageView),
    'nextCursor' : IDL.Opt(IDL.Text),
  });
  const NotificationType = IDL.Variant({
    'incomingCall' : IDL.Null,
    'groupInvite' : IDL.Null,
    'storyReply' : IDL.Null,
    'like' : IDL.Null,
    'postReaction' : IDL.Null,
    'comment' : IDL.Null,
    'message' : IDL.Null,
    'missedCall' : IDL.Null,
    'follow' : IDL.Null,
  });
  const NotificationView = IDL.Record({
    'id' : IDL.Text,
    'notifType' : NotificationType,
    'actorAvatarUrl' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'referenceId' : IDL.Opt(IDL.Text),
    'isRead' : IDL.Bool,
    'actorId' : IDL.Principal,
    'actorUsername' : IDL.Text,
    'recipientId' : IDL.Principal,
  });
  const Page_1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'items' : IDL.Vec(NotificationView),
    'nextCursor' : IDL.Opt(IDL.Text),
  });
  const UpsertProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'coverUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addComment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [CommentView],
        [],
      ),
    'addGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'createGroup' : IDL.Func([CreateGroupInput], [GroupChatView], []),
    'createPost' : IDL.Func([CreatePostInput], [PostView], []),
    'createStory' : IDL.Func([CreateStoryInput], [StoryView], []),
    'deleteComment' : IDL.Func([IDL.Text], [], []),
    'deleteGroup' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'demoteGroupAdmin' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'endCall' : IDL.Func([IDL.Text], [CallView], []),
    'follow' : IDL.Func([IDL.Principal], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
    'getCallHistory' : IDL.Func([IDL.Opt(IDL.Text)], [Page_4], ['query']),
    'getChatSettings' : IDL.Func([IDL.Principal], [ChatSettings], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(CommentView)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getGroupChats' : IDL.Func([], [IDL.Vec(GroupChatView)], ['query']),
    'getGroupMessages' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [Page_3],
        ['query'],
      ),
    'getHomeFeed' : IDL.Func([IDL.Opt(IDL.Text)], [Page], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Text)],
        [Page_2],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
    'getNotifications' : IDL.Func([IDL.Opt(IDL.Text)], [Page_1], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(PostView)], ['query']),
    'getPostReactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PostReactionSummary)],
        ['query'],
      ),
    'getProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getStoryViewers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfileView)],
        ['query'],
      ),
    'getSuggestedUsers' : IDL.Func([], [IDL.Vec(UserProfileView)], ['query']),
    'getTrendingPosts' : IDL.Func([IDL.Opt(IDL.Text)], [Page], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserPosts' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Text)],
        [Page],
        ['query'],
      ),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'leaveGroup' : IDL.Func([IDL.Text], [], []),
    'likeComment' : IDL.Func([IDL.Text], [], []),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'listFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UserProfileView)],
        ['query'],
      ),
    'listFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UserProfileView)],
        ['query'],
      ),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markAsRead' : IDL.Func([IDL.Principal], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'promoteGroupAdmin' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'reactToMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'reactToPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'removePostReaction' : IDL.Func([IDL.Text], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfileView)], ['query']),
    'sendGroupMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [GroupMessageView],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [MessageView],
        [],
      ),
    'startCall' : IDL.Func([IDL.Principal], [CallView], []),
    'unfollow' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
    'updateCallStatus' : IDL.Func([IDL.Text, CallStatus], [CallView], []),
    'updateChatSettings' : IDL.Func([IDL.Principal, ChatSettings], [], []),
    'updateGroupInfo' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [GroupChatView],
        [],
      ),
    'upsertProfile' : IDL.Func([UpsertProfileInput], [UserProfileView], []),
    'viewStory' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };