/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CallStatus = { 'active' : null } |
  { 'ringing' : null } |
  { 'missed' : null } |
  { 'ended' : null } |
  { 'declined' : null };
export interface CallView {
  'status' : CallStatus,
  'startedAt' : Timestamp,
  'callerAvatarUrl' : [] | [string],
  'endedAt' : [] | [Timestamp],
  'recipientDisplayName' : string,
  'recipientAvatarUrl' : [] | [string],
  'callerId' : Principal,
  'groupId' : [] | [string],
  'callerUsername' : string,
  'callId' : string,
  'recipientUsername' : string,
  'recipientId' : Principal,
  'callerDisplayName' : string,
}
export interface ChatSettings {
  'wallpaper' : [] | [string],
  'isArchived' : boolean,
  'muteUntil' : [] | [Timestamp],
  'bubbleColorReceived' : [] | [string],
  'isMuted' : boolean,
  'disappearingMode' : DisappearingMode,
  'chatName' : [] | [string],
  'bubbleColorSent' : [] | [string],
}
export interface CommentView {
  'id' : string,
  'authorUsername' : string,
  'content' : string,
  'authorId' : Principal,
  'createdAt' : Timestamp,
  'authorAvatarUrl' : [] | [string],
  'parentId' : [] | [string],
  'likesCount' : bigint,
  'authorDisplayName' : string,
  'likedByMe' : boolean,
  'postId' : string,
}
export interface Conversation {
  'lastMessageAt' : Timestamp,
  'lastMessage' : [] | [string],
  'participantId' : Principal,
  'unreadCount' : bigint,
}
export interface CreateGroupInput {
  'name' : string,
  'avatarUrl' : [] | [string],
  'memberIds' : Array<Principal>,
}
export interface CreatePostInput {
  'moodTag' : [] | [string],
  'mediaUrl' : [] | [string],
  'caption' : string,
  'visibility' : PostVisibility,
}
export interface CreateStoryInput {
  'moodTag' : [] | [string],
  'mediaUrl' : [] | [string],
  'caption' : [] | [string],
}
export type DisappearingMode = { 'd7' : null } |
  { 'h24' : null } |
  { 'off' : null };
export interface GroupChatView {
  'members' : Array<Principal>,
  'lastMessageAt' : [] | [Timestamp],
  'adminIds' : Array<Principal>,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'lastMessage' : [] | [string],
  'memberProfiles' : Array<UserProfileView>,
  'groupId' : string,
  'avatarUrl' : [] | [string],
  'unreadCount' : bigint,
}
export interface GroupMessageView {
  'id' : string,
  'status' : MessageStatus,
  'senderAvatarUrl' : [] | [string],
  'content' : string,
  'createdAt' : Timestamp,
  'senderUsername' : string,
  'senderDisplayName' : string,
  'mediaUrl' : [] | [string],
  'groupId' : string,
  'fromId' : Principal,
  'replyToId' : [] | [string],
  'reactions' : Array<[string, Array<Principal>]>,
}
export type MessageStatus = { 'read' : null } |
  { 'sent' : null } |
  { 'sending' : null } |
  { 'delivered' : null };
export interface MessageView {
  'id' : string,
  'status' : MessageStatus,
  'content' : string,
  'createdAt' : Timestamp,
  'toId' : Principal,
  'emojiReaction' : [] | [string],
  'mediaUrl' : [] | [string],
  'disappearsAt' : [] | [Timestamp],
  'fromId' : Principal,
  'replyToId' : [] | [string],
}
export type NotificationType = { 'incomingCall' : null } |
  { 'groupInvite' : null } |
  { 'storyReply' : null } |
  { 'like' : null } |
  { 'postReaction' : null } |
  { 'comment' : null } |
  { 'message' : null } |
  { 'missedCall' : null } |
  { 'follow' : null };
export interface NotificationView {
  'id' : string,
  'notifType' : NotificationType,
  'actorAvatarUrl' : [] | [string],
  'createdAt' : Timestamp,
  'referenceId' : [] | [string],
  'isRead' : boolean,
  'actorId' : Principal,
  'actorUsername' : string,
  'recipientId' : Principal,
}
export interface Page {
  'hasMore' : boolean,
  'items' : Array<PostView>,
  'nextCursor' : [] | [string],
}
export interface Page_1 {
  'hasMore' : boolean,
  'items' : Array<NotificationView>,
  'nextCursor' : [] | [string],
}
export interface Page_2 {
  'hasMore' : boolean,
  'items' : Array<MessageView>,
  'nextCursor' : [] | [string],
}
export interface Page_3 {
  'hasMore' : boolean,
  'items' : Array<GroupMessageView>,
  'nextCursor' : [] | [string],
}
export interface Page_4 {
  'hasMore' : boolean,
  'items' : Array<CallView>,
  'nextCursor' : [] | [string],
}
export interface PostReactionSummary {
  'reactedByMe' : boolean,
  'count' : bigint,
  'emoji' : string,
}
export interface PostView {
  'id' : string,
  'authorUsername' : string,
  'authorId' : Principal,
  'moodTag' : [] | [string],
  'createdAt' : Timestamp,
  'mediaUrl' : [] | [string],
  'authorAvatarUrl' : [] | [string],
  'caption' : string,
  'commentsCount' : bigint,
  'likesCount' : bigint,
  'visibility' : PostVisibility,
  'authorDisplayName' : string,
  'reactions' : Array<PostReactionSummary>,
  'likedByMe' : boolean,
}
export type PostVisibility = { 'everyone' : null } |
  { 'followers' : null };
export interface StoryView {
  'id' : string,
  'authorUsername' : string,
  'expiresAt' : Timestamp,
  'viewedByMe' : boolean,
  'authorId' : Principal,
  'moodTag' : [] | [string],
  'createdAt' : Timestamp,
  'mediaUrl' : [] | [string],
  'authorAvatarUrl' : [] | [string],
  'caption' : [] | [string],
  'authorDisplayName' : string,
  'viewsCount' : bigint,
}
export type Timestamp = bigint;
export interface UpsertProfileInput {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'avatarUrl' : [] | [string],
  'coverUrl' : [] | [string],
}
export interface UserProfileView {
  'id' : Principal,
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'followersCount' : bigint,
  'createdAt' : Timestamp,
  'isVerified' : boolean,
  'avatarUrl' : [] | [string],
  'isFollowing' : boolean,
  'followingCount' : bigint,
  'coverUrl' : [] | [string],
  'postsCount' : bigint,
}
export interface _SERVICE {
  'addComment' : ActorMethod<[string, string, [] | [string]], CommentView>,
  'addGroupMember' : ActorMethod<[string, Principal], undefined>,
  'createGroup' : ActorMethod<[CreateGroupInput], GroupChatView>,
  'createPost' : ActorMethod<[CreatePostInput], PostView>,
  'createStory' : ActorMethod<[CreateStoryInput], StoryView>,
  'deleteComment' : ActorMethod<[string], undefined>,
  'deleteGroup' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'demoteGroupAdmin' : ActorMethod<[string, Principal], undefined>,
  'endCall' : ActorMethod<[string], CallView>,
  'follow' : ActorMethod<[Principal], undefined>,
  'getActiveStories' : ActorMethod<[], Array<StoryView>>,
  'getCallHistory' : ActorMethod<[[] | [string]], Page_4>,
  'getChatSettings' : ActorMethod<[Principal], ChatSettings>,
  'getComments' : ActorMethod<[string], Array<CommentView>>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getGroupChats' : ActorMethod<[], Array<GroupChatView>>,
  'getGroupMessages' : ActorMethod<[string, [] | [string]], Page_3>,
  'getHomeFeed' : ActorMethod<[[] | [string]], Page>,
  'getMessages' : ActorMethod<[Principal, [] | [string]], Page_2>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getNotifications' : ActorMethod<[[] | [string]], Page_1>,
  'getPost' : ActorMethod<[string], [] | [PostView]>,
  'getPostReactions' : ActorMethod<[string], Array<PostReactionSummary>>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'getStoryViewers' : ActorMethod<[string], Array<UserProfileView>>,
  'getSuggestedUsers' : ActorMethod<[], Array<UserProfileView>>,
  'getTrendingPosts' : ActorMethod<[[] | [string]], Page>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserPosts' : ActorMethod<[Principal, [] | [string]], Page>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'leaveGroup' : ActorMethod<[string], undefined>,
  'likeComment' : ActorMethod<[string], undefined>,
  'likePost' : ActorMethod<[string], undefined>,
  'listFollowers' : ActorMethod<[Principal], Array<UserProfileView>>,
  'listFollowing' : ActorMethod<[Principal], Array<UserProfileView>>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markAsRead' : ActorMethod<[Principal], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'promoteGroupAdmin' : ActorMethod<[string, Principal], undefined>,
  'reactToMessage' : ActorMethod<[string, string], undefined>,
  'reactToPost' : ActorMethod<[string, string], undefined>,
  'removeGroupMember' : ActorMethod<[string, Principal], undefined>,
  'removePostReaction' : ActorMethod<[string], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserProfileView>>,
  'sendGroupMessage' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    GroupMessageView
  >,
  'sendMessage' : ActorMethod<
    [Principal, string, [] | [string], [] | [string]],
    MessageView
  >,
  'startCall' : ActorMethod<[Principal], CallView>,
  'unfollow' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[string], undefined>,
  'updateCallStatus' : ActorMethod<[string, CallStatus], CallView>,
  'updateChatSettings' : ActorMethod<[Principal, ChatSettings], undefined>,
  'updateGroupInfo' : ActorMethod<
    [string, [] | [string], [] | [string]],
    GroupChatView
  >,
  'upsertProfile' : ActorMethod<[UpsertProfileInput], UserProfileView>,
  'viewStory' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];