/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface GroupMessageView {
    id: string;
    status: MessageStatus;
    senderAvatarUrl?: string;
    content: string;
    createdAt: Timestamp;
    senderUsername: string;
    senderDisplayName: string;
    mediaUrl?: string;
    groupId: string;
    fromId: Principal;
    replyToId?: string;
    reactions: Array<[string, Array<Principal>]>;
}
export interface PostView {
    id: string;
    authorUsername: string;
    authorId: Principal;
    moodTag?: string;
    createdAt: Timestamp;
    mediaUrl?: string;
    authorAvatarUrl?: string;
    caption: string;
    commentsCount: bigint;
    likesCount: bigint;
    visibility: PostVisibility;
    authorDisplayName: string;
    reactions: Array<PostReactionSummary>;
    likedByMe: boolean;
}
export interface Page_2 {
    hasMore: boolean;
    items: Array<MessageView>;
    nextCursor?: string;
}
export interface CreatePostInput {
    moodTag?: string;
    mediaUrl?: string;
    caption: string;
    visibility: PostVisibility;
}
export interface ChatSettings {
    wallpaper?: string;
    isArchived: boolean;
    muteUntil?: Timestamp;
    bubbleColorReceived?: string;
    isMuted: boolean;
    disappearingMode: DisappearingMode;
    chatName?: string;
    bubbleColorSent?: string;
}
export interface Page_1 {
    hasMore: boolean;
    items: Array<NotificationView>;
    nextCursor?: string;
}
export interface CommentView {
    id: string;
    authorUsername: string;
    content: string;
    authorId: Principal;
    createdAt: Timestamp;
    authorAvatarUrl?: string;
    parentId?: string;
    likesCount: bigint;
    authorDisplayName: string;
    likedByMe: boolean;
    postId: string;
}
export interface UpsertProfileInput {
    bio: string;
    username: string;
    displayName: string;
    avatarUrl?: string;
    coverUrl?: string;
}
export interface NotificationView {
    id: string;
    notifType: NotificationType;
    actorAvatarUrl?: string;
    createdAt: Timestamp;
    referenceId?: string;
    isRead: boolean;
    actorId: Principal;
    actorUsername: string;
    recipientId: Principal;
}
export interface GroupChatView {
    members: Array<Principal>;
    lastMessageAt?: Timestamp;
    adminIds: Array<Principal>;
    name: string;
    createdAt: Timestamp;
    createdBy: Principal;
    lastMessage?: string;
    memberProfiles: Array<UserProfileView>;
    groupId: string;
    avatarUrl?: string;
    unreadCount: bigint;
}
export interface Page_3 {
    hasMore: boolean;
    items: Array<GroupMessageView>;
    nextCursor?: string;
}
export interface Page {
    hasMore: boolean;
    items: Array<PostView>;
    nextCursor?: string;
}
export interface CallView {
    status: CallStatus;
    startedAt: Timestamp;
    callerAvatarUrl?: string;
    endedAt?: Timestamp;
    recipientDisplayName: string;
    recipientAvatarUrl?: string;
    callerId: Principal;
    groupId?: string;
    callerUsername: string;
    callId: string;
    recipientUsername: string;
    recipientId: Principal;
    callerDisplayName: string;
}
export interface StoryView {
    id: string;
    authorUsername: string;
    expiresAt: Timestamp;
    viewedByMe: boolean;
    authorId: Principal;
    moodTag?: string;
    createdAt: Timestamp;
    mediaUrl?: string;
    authorAvatarUrl?: string;
    caption?: string;
    authorDisplayName: string;
    viewsCount: bigint;
}
export interface UserProfileView {
    id: Principal;
    bio: string;
    username: string;
    displayName: string;
    followersCount: bigint;
    createdAt: Timestamp;
    isVerified: boolean;
    avatarUrl?: string;
    isFollowing: boolean;
    followingCount: bigint;
    coverUrl?: string;
    postsCount: bigint;
}
export interface MessageView {
    id: string;
    status: MessageStatus;
    content: string;
    createdAt: Timestamp;
    toId: Principal;
    emojiReaction?: string;
    mediaUrl?: string;
    disappearsAt?: Timestamp;
    fromId: Principal;
    replyToId?: string;
}
export interface CreateStoryInput {
    moodTag?: string;
    mediaUrl?: string;
    caption?: string;
}
export interface PostReactionSummary {
    reactedByMe: boolean;
    count: bigint;
    emoji: string;
}
export interface Page_4 {
    hasMore: boolean;
    items: Array<CallView>;
    nextCursor?: string;
}
export interface Conversation {
    lastMessageAt: Timestamp;
    lastMessage?: string;
    participantId: Principal;
    unreadCount: bigint;
}
export interface CreateGroupInput {
    name: string;
    avatarUrl?: string;
    memberIds: Array<Principal>;
}
export enum CallStatus {
    active = "active",
    ringing = "ringing",
    missed = "missed",
    ended = "ended",
    declined = "declined"
}
export enum DisappearingMode {
    d7 = "d7",
    h24 = "h24",
    off = "off"
}
export enum MessageStatus {
    read = "read",
    sent = "sent",
    sending = "sending",
    delivered = "delivered"
}
export enum NotificationType {
    incomingCall = "incomingCall",
    groupInvite = "groupInvite",
    storyReply = "storyReply",
    like = "like",
    postReaction = "postReaction",
    comment = "comment",
    message = "message",
    missedCall = "missedCall",
    follow = "follow"
}
export enum PostVisibility {
    everyone = "everyone",
    followers = "followers"
}
export interface backendInterface {
    addComment(postId: string, content: string, parentId: string | null): Promise<CommentView>;
    addGroupMember(groupId: string, userId: Principal): Promise<void>;
    createGroup(input: CreateGroupInput): Promise<GroupChatView>;
    createPost(input: CreatePostInput): Promise<PostView>;
    createStory(input: CreateStoryInput): Promise<StoryView>;
    deleteComment(id: string): Promise<void>;
    deleteGroup(groupId: string): Promise<void>;
    deletePost(id: string): Promise<void>;
    demoteGroupAdmin(groupId: string, userId: Principal): Promise<void>;
    endCall(callId: string): Promise<CallView>;
    follow(userId: Principal): Promise<void>;
    getActiveStories(): Promise<Array<StoryView>>;
    getCallHistory(cursor: string | null): Promise<Page_4>;
    getChatSettings(userId: Principal): Promise<ChatSettings>;
    getComments(postId: string): Promise<Array<CommentView>>;
    getConversations(): Promise<Array<Conversation>>;
    getFollowers(userId: Principal): Promise<Array<Principal>>;
    getFollowing(userId: Principal): Promise<Array<Principal>>;
    getGroupChats(): Promise<Array<GroupChatView>>;
    getGroupMessages(groupId: string, cursor: string | null): Promise<Page_3>;
    getHomeFeed(cursor: string | null): Promise<Page>;
    getMessages(userId: Principal, cursor: string | null): Promise<Page_2>;
    getMyProfile(): Promise<UserProfileView | null>;
    getNotifications(cursor: string | null): Promise<Page_1>;
    getPost(id: string): Promise<PostView | null>;
    getPostReactions(postId: string): Promise<Array<PostReactionSummary>>;
    getProfile(userId: Principal): Promise<UserProfileView | null>;
    getStoryViewers(id: string): Promise<Array<UserProfileView>>;
    getSuggestedUsers(): Promise<Array<UserProfileView>>;
    getTrendingPosts(cursor: string | null): Promise<Page>;
    getUnreadCount(): Promise<bigint>;
    getUserPosts(userId: Principal, cursor: string | null): Promise<Page>;
    isFollowing(userId: Principal): Promise<boolean>;
    leaveGroup(groupId: string): Promise<void>;
    likeComment(id: string): Promise<void>;
    likePost(id: string): Promise<void>;
    listFollowers(userId: Principal): Promise<Array<UserProfileView>>;
    listFollowing(userId: Principal): Promise<Array<UserProfileView>>;
    markAllNotificationsRead(): Promise<void>;
    markAsRead(userId: Principal): Promise<void>;
    markNotificationRead(id: string): Promise<void>;
    promoteGroupAdmin(groupId: string, userId: Principal): Promise<void>;
    reactToMessage(messageId: string, emoji: string): Promise<void>;
    reactToPost(postId: string, emoji: string): Promise<void>;
    removeGroupMember(groupId: string, userId: Principal): Promise<void>;
    removePostReaction(postId: string): Promise<void>;
    searchUsers(searchTerm: string): Promise<Array<UserProfileView>>;
    sendGroupMessage(groupId: string, content: string, mediaUrl: string | null, replyToId: string | null): Promise<GroupMessageView>;
    sendMessage(toId: Principal, content: string, mediaUrl: string | null, replyToId: string | null): Promise<MessageView>;
    startCall(recipientId: Principal): Promise<CallView>;
    unfollow(userId: Principal): Promise<void>;
    unlikePost(id: string): Promise<void>;
    updateCallStatus(callId: string, status: CallStatus): Promise<CallView>;
    updateChatSettings(userId: Principal, settings: ChatSettings): Promise<void>;
    updateGroupInfo(groupId: string, name: string | null, avatarUrl: string | null): Promise<GroupChatView>;
    upsertProfile(input: UpsertProfileInput): Promise<UserProfileView>;
    viewStory(id: string): Promise<void>;
}
import type { CallStatus as _CallStatus, CallView as _CallView, ChatSettings as _ChatSettings, CommentView as _CommentView, Conversation as _Conversation, CreateGroupInput as _CreateGroupInput, CreatePostInput as _CreatePostInput, CreateStoryInput as _CreateStoryInput, DisappearingMode as _DisappearingMode, GroupChatView as _GroupChatView, GroupMessageView as _GroupMessageView, MessageStatus as _MessageStatus, MessageView as _MessageView, NotificationType as _NotificationType, NotificationView as _NotificationView, Page as _Page, Page_1 as _Page_1, Page_2 as _Page_2, Page_3 as _Page_3, Page_4 as _Page_4, PostReactionSummary as _PostReactionSummary, PostView as _PostView, PostVisibility as _PostVisibility, StoryView as _StoryView, Timestamp as _Timestamp, UpsertProfileInput as _UpsertProfileInput, UserProfileView as _UserProfileView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: string, arg1: string, arg2: string | null): Promise<CommentView> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_CommentView_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_CommentView_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addGroupMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupMember(arg0, arg1);
            return result;
        }
    }
    async createGroup(arg0: CreateGroupInput): Promise<GroupChatView> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(to_candid_CreateGroupInput_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GroupChatView_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(to_candid_CreateGroupInput_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GroupChatView_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPost(arg0: CreatePostInput): Promise<PostView> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_CreatePostInput_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PostView_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_CreatePostInput_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PostView_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStory(arg0: CreateStoryInput): Promise<StoryView> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(to_candid_CreateStoryInput_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_StoryView_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(to_candid_CreateStoryInput_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_StoryView_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroup(arg0);
            return result;
        }
    }
    async deletePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async demoteGroupAdmin(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.demoteGroupAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.demoteGroupAdmin(arg0, arg1);
            return result;
        }
    }
    async endCall(arg0: string): Promise<CallView> {
        if (this.processError) {
            try {
                const result = await this.actor.endCall(arg0);
                return from_candid_CallView_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endCall(arg0);
            return from_candid_CallView_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async follow(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.follow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.follow(arg0);
            return result;
        }
    }
    async getActiveStories(): Promise<Array<StoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStories();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStories();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallHistory(arg0: string | null): Promise<Page_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallHistory(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Page_4_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallHistory(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Page_4_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatSettings(arg0: Principal): Promise<ChatSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatSettings(arg0);
                return from_candid_ChatSettings_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatSettings(arg0);
            return from_candid_ChatSettings_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: string): Promise<Array<CommentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowing(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return result;
        }
    }
    async getGroupChats(): Promise<Array<GroupChatView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupChats();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupChats();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupMessages(arg0: string, arg1: string | null): Promise<Page_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMessages(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Page_3_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMessages(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Page_3_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomeFeed(arg0: string | null): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeFeed(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Page_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeFeed(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Page_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: Principal, arg1: string | null): Promise<Page_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Page_2_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Page_2_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: string | null): Promise<Page_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Page_1_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Page_1_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: string): Promise<PostView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostReactions(arg0: string): Promise<Array<PostReactionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostReactions(arg0);
            return result;
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoryViewers(arg0: string): Promise<Array<UserProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoryViewers(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoryViewers(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuggestedUsers(): Promise<Array<UserProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestedUsers();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestedUsers();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingPosts(arg0: string | null): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingPosts(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Page_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingPosts(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Page_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async getUserPosts(arg0: Principal, arg1: string | null): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPosts(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Page_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPosts(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Page_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async isFollowing(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0);
            return result;
        }
    }
    async leaveGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return result;
        }
    }
    async likeComment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeComment(arg0);
            return result;
        }
    }
    async likePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async listFollowers(arg0: Principal): Promise<Array<UserProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFollowers(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFollowers(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFollowing(arg0: Principal): Promise<Array<UserProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFollowing(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFollowing(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markAsRead(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsRead(arg0);
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async promoteGroupAdmin(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteGroupAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteGroupAdmin(arg0, arg1);
            return result;
        }
    }
    async reactToMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactToMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactToMessage(arg0, arg1);
            return result;
        }
    }
    async reactToPost(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactToPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactToPost(arg0, arg1);
            return result;
        }
    }
    async removeGroupMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGroupMember(arg0, arg1);
            return result;
        }
    }
    async removePostReaction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePostReaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePostReaction(arg0);
            return result;
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendGroupMessage(arg0: string, arg1: string, arg2: string | null, arg3: string | null): Promise<GroupMessageView> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGroupMessage(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_GroupMessageView_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGroupMessage(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_GroupMessageView_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: Principal, arg1: string, arg2: string | null, arg3: string | null): Promise<MessageView> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_MessageView_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_MessageView_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async startCall(arg0: Principal): Promise<CallView> {
        if (this.processError) {
            try {
                const result = await this.actor.startCall(arg0);
                return from_candid_CallView_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startCall(arg0);
            return from_candid_CallView_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async unfollow(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollow(arg0);
            return result;
        }
    }
    async unlikePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async updateCallStatus(arg0: string, arg1: CallStatus): Promise<CallView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallStatus(arg0, to_candid_CallStatus_n66(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CallView_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallStatus(arg0, to_candid_CallStatus_n66(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CallView_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateChatSettings(arg0: Principal, arg1: ChatSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChatSettings(arg0, to_candid_ChatSettings_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChatSettings(arg0, to_candid_ChatSettings_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateGroupInfo(arg0: string, arg1: string | null, arg2: string | null): Promise<GroupChatView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGroupInfo(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_GroupChatView_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGroupInfo(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_GroupChatView_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertProfile(arg0: UpsertProfileInput): Promise<UserProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertProfile(to_candid_UpsertProfileInput_n72(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfileView_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertProfile(to_candid_UpsertProfileInput_n72(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfileView_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async viewStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.viewStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewStory(arg0);
            return result;
        }
    }
}
function from_candid_CallStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatus): CallStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_CallView_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallView): CallView {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ChatSettings_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatSettings): ChatSettings {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_CommentView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommentView): CommentView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Conversation_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_DisappearingMode_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisappearingMode): DisappearingMode {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_GroupChatView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupChatView): GroupChatView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_GroupMessageView_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupMessageView): GroupMessageView {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_MessageStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageStatus): MessageStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_MessageView_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageView): MessageView {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationView_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationView): NotificationView {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Page_1_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_1): Page_1 {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Page_2_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_2): Page_2 {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Page_3_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_3): Page_3 {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Page_4_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_4): Page_4 {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Page_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Page {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_PostView_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostView): PostView {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PostVisibility_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostVisibility): PostVisibility {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StoryView_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryView): StoryView {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfileView_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileView): UserProfileView {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : from_candid_UserProfileView_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostView]): PostView | null {
    return value.length === 0 ? null : from_candid_PostView_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: string;
    username: string;
    displayName: string;
    followersCount: bigint;
    createdAt: _Timestamp;
    isVerified: boolean;
    avatarUrl: [] | [string];
    isFollowing: boolean;
    followingCount: bigint;
    coverUrl: [] | [string];
    postsCount: bigint;
}): {
    id: Principal;
    bio: string;
    username: string;
    displayName: string;
    followersCount: bigint;
    createdAt: Timestamp;
    isVerified: boolean;
    avatarUrl?: string;
    isFollowing: boolean;
    followingCount: bigint;
    coverUrl?: string;
    postsCount: bigint;
} {
    return {
        id: value.id,
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        followersCount: value.followersCount,
        createdAt: value.createdAt,
        isVerified: value.isVerified,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.avatarUrl)),
        isFollowing: value.isFollowing,
        followingCount: value.followingCount,
        coverUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.coverUrl)),
        postsCount: value.postsCount
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    authorUsername: string;
    authorId: Principal;
    moodTag: [] | [string];
    createdAt: _Timestamp;
    mediaUrl: [] | [string];
    authorAvatarUrl: [] | [string];
    caption: string;
    commentsCount: bigint;
    likesCount: bigint;
    visibility: _PostVisibility;
    authorDisplayName: string;
    reactions: Array<_PostReactionSummary>;
    likedByMe: boolean;
}): {
    id: string;
    authorUsername: string;
    authorId: Principal;
    moodTag?: string;
    createdAt: Timestamp;
    mediaUrl?: string;
    authorAvatarUrl?: string;
    caption: string;
    commentsCount: bigint;
    likesCount: bigint;
    visibility: PostVisibility;
    authorDisplayName: string;
    reactions: Array<PostReactionSummary>;
    likedByMe: boolean;
} {
    return {
        id: value.id,
        authorUsername: value.authorUsername,
        authorId: value.authorId,
        moodTag: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.moodTag)),
        createdAt: value.createdAt,
        mediaUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.mediaUrl)),
        authorAvatarUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.authorAvatarUrl)),
        caption: value.caption,
        commentsCount: value.commentsCount,
        likesCount: value.likesCount,
        visibility: from_candid_PostVisibility_n19(_uploadFile, _downloadFile, value.visibility),
        authorDisplayName: value.authorDisplayName,
        reactions: value.reactions,
        likedByMe: value.likedByMe
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    authorUsername: string;
    expiresAt: _Timestamp;
    viewedByMe: boolean;
    authorId: Principal;
    moodTag: [] | [string];
    createdAt: _Timestamp;
    mediaUrl: [] | [string];
    authorAvatarUrl: [] | [string];
    caption: [] | [string];
    authorDisplayName: string;
    viewsCount: bigint;
}): {
    id: string;
    authorUsername: string;
    expiresAt: Timestamp;
    viewedByMe: boolean;
    authorId: Principal;
    moodTag?: string;
    createdAt: Timestamp;
    mediaUrl?: string;
    authorAvatarUrl?: string;
    caption?: string;
    authorDisplayName: string;
    viewsCount: bigint;
} {
    return {
        id: value.id,
        authorUsername: value.authorUsername,
        expiresAt: value.expiresAt,
        viewedByMe: value.viewedByMe,
        authorId: value.authorId,
        moodTag: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.moodTag)),
        createdAt: value.createdAt,
        mediaUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.mediaUrl)),
        authorAvatarUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.authorAvatarUrl)),
        caption: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.caption)),
        authorDisplayName: value.authorDisplayName,
        viewsCount: value.viewsCount
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CallStatus;
    startedAt: _Timestamp;
    callerAvatarUrl: [] | [string];
    endedAt: [] | [_Timestamp];
    recipientDisplayName: string;
    recipientAvatarUrl: [] | [string];
    callerId: Principal;
    groupId: [] | [string];
    callerUsername: string;
    callId: string;
    recipientUsername: string;
    recipientId: Principal;
    callerDisplayName: string;
}): {
    status: CallStatus;
    startedAt: Timestamp;
    callerAvatarUrl?: string;
    endedAt?: Timestamp;
    recipientDisplayName: string;
    recipientAvatarUrl?: string;
    callerId: Principal;
    groupId?: string;
    callerUsername: string;
    callId: string;
    recipientUsername: string;
    recipientId: Principal;
    callerDisplayName: string;
} {
    return {
        status: from_candid_CallStatus_n27(_uploadFile, _downloadFile, value.status),
        startedAt: value.startedAt,
        callerAvatarUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.callerAvatarUrl)),
        endedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.endedAt)),
        recipientDisplayName: value.recipientDisplayName,
        recipientAvatarUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.recipientAvatarUrl)),
        callerId: value.callerId,
        groupId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.groupId)),
        callerUsername: value.callerUsername,
        callId: value.callId,
        recipientUsername: value.recipientUsername,
        recipientId: value.recipientId,
        callerDisplayName: value.callerDisplayName
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    authorUsername: string;
    content: string;
    authorId: Principal;
    createdAt: _Timestamp;
    authorAvatarUrl: [] | [string];
    parentId: [] | [string];
    likesCount: bigint;
    authorDisplayName: string;
    likedByMe: boolean;
    postId: string;
}): {
    id: string;
    authorUsername: string;
    content: string;
    authorId: Principal;
    createdAt: Timestamp;
    authorAvatarUrl?: string;
    parentId?: string;
    likesCount: bigint;
    authorDisplayName: string;
    likedByMe: boolean;
    postId: string;
} {
    return {
        id: value.id,
        authorUsername: value.authorUsername,
        content: value.content,
        authorId: value.authorId,
        createdAt: value.createdAt,
        authorAvatarUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.authorAvatarUrl)),
        parentId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.parentId)),
        likesCount: value.likesCount,
        authorDisplayName: value.authorDisplayName,
        likedByMe: value.likedByMe,
        postId: value.postId
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    items: Array<_CallView>;
    nextCursor: [] | [string];
}): {
    hasMore: boolean;
    items: Array<CallView>;
    nextCursor?: string;
} {
    return {
        hasMore: value.hasMore,
        items: from_candid_vec_n32(_uploadFile, _downloadFile, value.items),
        nextCursor: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wallpaper: [] | [string];
    isArchived: boolean;
    muteUntil: [] | [_Timestamp];
    bubbleColorReceived: [] | [string];
    isMuted: boolean;
    disappearingMode: _DisappearingMode;
    chatName: [] | [string];
    bubbleColorSent: [] | [string];
}): {
    wallpaper?: string;
    isArchived: boolean;
    muteUntil?: Timestamp;
    bubbleColorReceived?: string;
    isMuted: boolean;
    disappearingMode: DisappearingMode;
    chatName?: string;
    bubbleColorSent?: string;
} {
    return {
        wallpaper: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.wallpaper)),
        isArchived: value.isArchived,
        muteUntil: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.muteUntil)),
        bubbleColorReceived: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.bubbleColorReceived)),
        isMuted: value.isMuted,
        disappearingMode: from_candid_DisappearingMode_n35(_uploadFile, _downloadFile, value.disappearingMode),
        chatName: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.chatName)),
        bubbleColorSent: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.bubbleColorSent))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastMessageAt: _Timestamp;
    lastMessage: [] | [string];
    participantId: Principal;
    unreadCount: bigint;
}): {
    lastMessageAt: Timestamp;
    lastMessage?: string;
    participantId: Principal;
    unreadCount: bigint;
} {
    return {
        lastMessageAt: value.lastMessageAt,
        lastMessage: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.lastMessage)),
        participantId: value.participantId,
        unreadCount: value.unreadCount
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    items: Array<_GroupMessageView>;
    nextCursor: [] | [string];
}): {
    hasMore: boolean;
    items: Array<GroupMessageView>;
    nextCursor?: string;
} {
    return {
        hasMore: value.hasMore,
        items: from_candid_vec_n44(_uploadFile, _downloadFile, value.items),
        nextCursor: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _MessageStatus;
    senderAvatarUrl: [] | [string];
    content: string;
    createdAt: _Timestamp;
    senderUsername: string;
    senderDisplayName: string;
    mediaUrl: [] | [string];
    groupId: string;
    fromId: Principal;
    replyToId: [] | [string];
    reactions: Array<[string, Array<Principal>]>;
}): {
    id: string;
    status: MessageStatus;
    senderAvatarUrl?: string;
    content: string;
    createdAt: Timestamp;
    senderUsername: string;
    senderDisplayName: string;
    mediaUrl?: string;
    groupId: string;
    fromId: Principal;
    replyToId?: string;
    reactions: Array<[string, Array<Principal>]>;
} {
    return {
        id: value.id,
        status: from_candid_MessageStatus_n47(_uploadFile, _downloadFile, value.status),
        senderAvatarUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.senderAvatarUrl)),
        content: value.content,
        createdAt: value.createdAt,
        senderUsername: value.senderUsername,
        senderDisplayName: value.senderDisplayName,
        mediaUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.mediaUrl)),
        groupId: value.groupId,
        fromId: value.fromId,
        replyToId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.replyToId)),
        reactions: value.reactions
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    items: Array<_PostView>;
    nextCursor: [] | [string];
}): {
    hasMore: boolean;
    items: Array<PostView>;
    nextCursor?: string;
} {
    return {
        hasMore: value.hasMore,
        items: from_candid_vec_n51(_uploadFile, _downloadFile, value.items),
        nextCursor: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    items: Array<_MessageView>;
    nextCursor: [] | [string];
}): {
    hasMore: boolean;
    items: Array<MessageView>;
    nextCursor?: string;
} {
    return {
        hasMore: value.hasMore,
        items: from_candid_vec_n54(_uploadFile, _downloadFile, value.items),
        nextCursor: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _MessageStatus;
    content: string;
    createdAt: _Timestamp;
    toId: Principal;
    emojiReaction: [] | [string];
    mediaUrl: [] | [string];
    disappearsAt: [] | [_Timestamp];
    fromId: Principal;
    replyToId: [] | [string];
}): {
    id: string;
    status: MessageStatus;
    content: string;
    createdAt: Timestamp;
    toId: Principal;
    emojiReaction?: string;
    mediaUrl?: string;
    disappearsAt?: Timestamp;
    fromId: Principal;
    replyToId?: string;
} {
    return {
        id: value.id,
        status: from_candid_MessageStatus_n47(_uploadFile, _downloadFile, value.status),
        content: value.content,
        createdAt: value.createdAt,
        toId: value.toId,
        emojiReaction: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.emojiReaction)),
        mediaUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.mediaUrl)),
        disappearsAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.disappearsAt)),
        fromId: value.fromId,
        replyToId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.replyToId))
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    items: Array<_NotificationView>;
    nextCursor: [] | [string];
}): {
    hasMore: boolean;
    items: Array<NotificationView>;
    nextCursor?: string;
} {
    return {
        hasMore: value.hasMore,
        items: from_candid_vec_n60(_uploadFile, _downloadFile, value.items),
        nextCursor: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    notifType: _NotificationType;
    actorAvatarUrl: [] | [string];
    createdAt: _Timestamp;
    referenceId: [] | [string];
    isRead: boolean;
    actorId: Principal;
    actorUsername: string;
    recipientId: Principal;
}): {
    id: string;
    notifType: NotificationType;
    actorAvatarUrl?: string;
    createdAt: Timestamp;
    referenceId?: string;
    isRead: boolean;
    actorId: Principal;
    actorUsername: string;
    recipientId: Principal;
} {
    return {
        id: value.id,
        notifType: from_candid_NotificationType_n63(_uploadFile, _downloadFile, value.notifType),
        actorAvatarUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.actorAvatarUrl)),
        createdAt: value.createdAt,
        referenceId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.referenceId)),
        isRead: value.isRead,
        actorId: value.actorId,
        actorUsername: value.actorUsername,
        recipientId: value.recipientId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    members: Array<Principal>;
    lastMessageAt: [] | [_Timestamp];
    adminIds: Array<Principal>;
    name: string;
    createdAt: _Timestamp;
    createdBy: Principal;
    lastMessage: [] | [string];
    memberProfiles: Array<_UserProfileView>;
    groupId: string;
    avatarUrl: [] | [string];
    unreadCount: bigint;
}): {
    members: Array<Principal>;
    lastMessageAt?: Timestamp;
    adminIds: Array<Principal>;
    name: string;
    createdAt: Timestamp;
    createdBy: Principal;
    lastMessage?: string;
    memberProfiles: Array<UserProfileView>;
    groupId: string;
    avatarUrl?: string;
    unreadCount: bigint;
} {
    return {
        members: value.members,
        lastMessageAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.lastMessageAt)),
        adminIds: value.adminIds,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        lastMessage: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.lastMessage)),
        memberProfiles: from_candid_vec_n10(_uploadFile, _downloadFile, value.memberProfiles),
        groupId: value.groupId,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.avatarUrl)),
        unreadCount: value.unreadCount
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    everyone: null;
} | {
    followers: null;
}): PostVisibility {
    return "everyone" in value ? PostVisibility.everyone : "followers" in value ? PostVisibility.followers : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    ringing: null;
} | {
    missed: null;
} | {
    ended: null;
} | {
    declined: null;
}): CallStatus {
    return "active" in value ? CallStatus.active : "ringing" in value ? CallStatus.ringing : "missed" in value ? CallStatus.missed : "ended" in value ? CallStatus.ended : "declined" in value ? CallStatus.declined : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    d7: null;
} | {
    h24: null;
} | {
    off: null;
}): DisappearingMode {
    return "d7" in value ? DisappearingMode.d7 : "h24" in value ? DisappearingMode.h24 : "off" in value ? DisappearingMode.off : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    read: null;
} | {
    sent: null;
} | {
    sending: null;
} | {
    delivered: null;
}): MessageStatus {
    return "read" in value ? MessageStatus.read : "sent" in value ? MessageStatus.sent : "sending" in value ? MessageStatus.sending : "delivered" in value ? MessageStatus.delivered : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    incomingCall: null;
} | {
    groupInvite: null;
} | {
    storyReply: null;
} | {
    like: null;
} | {
    postReaction: null;
} | {
    comment: null;
} | {
    message: null;
} | {
    missedCall: null;
} | {
    follow: null;
}): NotificationType {
    return "incomingCall" in value ? NotificationType.incomingCall : "groupInvite" in value ? NotificationType.groupInvite : "storyReply" in value ? NotificationType.storyReply : "like" in value ? NotificationType.like : "postReaction" in value ? NotificationType.postReaction : "comment" in value ? NotificationType.comment : "message" in value ? NotificationType.message : "missedCall" in value ? NotificationType.missedCall : "follow" in value ? NotificationType.follow : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfileView>): Array<UserProfileView> {
    return value.map((x)=>from_candid_UserProfileView_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoryView>): Array<StoryView> {
    return value.map((x)=>from_candid_StoryView_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CallView>): Array<CallView> {
    return value.map((x)=>from_candid_CallView_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommentView>): Array<CommentView> {
    return value.map((x)=>from_candid_CommentView_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupChatView>): Array<GroupChatView> {
    return value.map((x)=>from_candid_GroupChatView_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupMessageView>): Array<GroupMessageView> {
    return value.map((x)=>from_candid_GroupMessageView_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostView>): Array<PostView> {
    return value.map((x)=>from_candid_PostView_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MessageView>): Array<MessageView> {
    return value.map((x)=>from_candid_MessageView_n55(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationView>): Array<NotificationView> {
    return value.map((x)=>from_candid_NotificationView_n61(_uploadFile, _downloadFile, x));
}
function to_candid_CallStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): _CallStatus {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_ChatSettings_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatSettings): _ChatSettings {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_CreateGroupInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateGroupInput): _CreateGroupInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CreatePostInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePostInput): _CreatePostInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_CreateStoryInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateStoryInput): _CreateStoryInput {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_DisappearingMode_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisappearingMode): _DisappearingMode {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_PostVisibility_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostVisibility): _PostVisibility {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UpsertProfileInput_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpsertProfileInput): _UpsertProfileInput {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moodTag?: string;
    mediaUrl?: string;
    caption: string;
    visibility: PostVisibility;
}): {
    moodTag: [] | [string];
    mediaUrl: [] | [string];
    caption: string;
    visibility: _PostVisibility;
} {
    return {
        moodTag: value.moodTag ? candid_some(value.moodTag) : candid_none(),
        mediaUrl: value.mediaUrl ? candid_some(value.mediaUrl) : candid_none(),
        caption: value.caption,
        visibility: to_candid_PostVisibility_n15(_uploadFile, _downloadFile, value.visibility)
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moodTag?: string;
    mediaUrl?: string;
    caption?: string;
}): {
    moodTag: [] | [string];
    mediaUrl: [] | [string];
    caption: [] | [string];
} {
    return {
        moodTag: value.moodTag ? candid_some(value.moodTag) : candid_none(),
        mediaUrl: value.mediaUrl ? candid_some(value.mediaUrl) : candid_none(),
        caption: value.caption ? candid_some(value.caption) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    avatarUrl?: string;
    memberIds: Array<Principal>;
}): {
    name: string;
    avatarUrl: [] | [string];
    memberIds: Array<Principal>;
} {
    return {
        name: value.name,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        memberIds: value.memberIds
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wallpaper?: string;
    isArchived: boolean;
    muteUntil?: Timestamp;
    bubbleColorReceived?: string;
    isMuted: boolean;
    disappearingMode: DisappearingMode;
    chatName?: string;
    bubbleColorSent?: string;
}): {
    wallpaper: [] | [string];
    isArchived: boolean;
    muteUntil: [] | [_Timestamp];
    bubbleColorReceived: [] | [string];
    isMuted: boolean;
    disappearingMode: _DisappearingMode;
    chatName: [] | [string];
    bubbleColorSent: [] | [string];
} {
    return {
        wallpaper: value.wallpaper ? candid_some(value.wallpaper) : candid_none(),
        isArchived: value.isArchived,
        muteUntil: value.muteUntil ? candid_some(value.muteUntil) : candid_none(),
        bubbleColorReceived: value.bubbleColorReceived ? candid_some(value.bubbleColorReceived) : candid_none(),
        isMuted: value.isMuted,
        disappearingMode: to_candid_DisappearingMode_n70(_uploadFile, _downloadFile, value.disappearingMode),
        chatName: value.chatName ? candid_some(value.chatName) : candid_none(),
        bubbleColorSent: value.bubbleColorSent ? candid_some(value.bubbleColorSent) : candid_none()
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: string;
    avatarUrl?: string;
    coverUrl?: string;
}): {
    bio: string;
    username: string;
    displayName: string;
    avatarUrl: [] | [string];
    coverUrl: [] | [string];
} {
    return {
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        coverUrl: value.coverUrl ? candid_some(value.coverUrl) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostVisibility): {
    everyone: null;
} | {
    followers: null;
} {
    return value == PostVisibility.everyone ? {
        everyone: null
    } : value == PostVisibility.followers ? {
        followers: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): {
    active: null;
} | {
    ringing: null;
} | {
    missed: null;
} | {
    ended: null;
} | {
    declined: null;
} {
    return value == CallStatus.active ? {
        active: null
    } : value == CallStatus.ringing ? {
        ringing: null
    } : value == CallStatus.missed ? {
        missed: null
    } : value == CallStatus.ended ? {
        ended: null
    } : value == CallStatus.declined ? {
        declined: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisappearingMode): {
    d7: null;
} | {
    h24: null;
} | {
    off: null;
} {
    return value == DisappearingMode.d7 ? {
        d7: null
    } : value == DisappearingMode.h24 ? {
        h24: null
    } : value == DisappearingMode.off ? {
        off: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
